package com.zaheer.emitrapalert.utils

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.zaheer.emitrapalert.domain.FinancialAnalysis
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfExporter {
    
    fun exportAnalysisToPdf(
        context: Context,
        monthlyIncome: Double,
        fixedExpenses: Double,
        totalEmis: Double,
        desiredSavings: Double,
        analysis: FinancialAnalysis
    ): File? {
        try {
            // Create file name with timestamp
            val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
            val fileName = "EMI_Analysis_$timestamp.pdf"
            
            // Create file in Downloads directory
            val file = if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
                File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), fileName)
            } else {
                File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), fileName)
            }
            
            // Create PDF writer
            val writer = PdfWriter(FileOutputStream(file))
            val pdfDocument = PdfDocument(writer)
            val document = Document(pdfDocument)
            
            // Add content
            document.add(Paragraph("EMI Trap Alert - Financial Analysis Report")
                .setBold()
                .setFontSize(20f))
            document.add(Paragraph("\nGenerated on: ${SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date())}"))
            
            document.add(Paragraph("\n--- Input Details ---").setBold())
            document.add(Paragraph("Monthly Net Income: ₹${String.format("%.2f", monthlyIncome)}"))
            document.add(Paragraph("Fixed Monthly Expenses: ₹${String.format("%.2f", fixedExpenses)}"))
            document.add(Paragraph("Total EMIs per Month: ₹${String.format("%.2f", totalEmis)}"))
            document.add(Paragraph("Desired Savings: ₹${String.format("%.2f", desiredSavings)}"))
            
            document.add(Paragraph("\n--- Analysis Results ---").setBold())
            document.add(Paragraph("Debt-to-Income Ratio: ${String.format("%.2f", analysis.dtiRatio)}%"))
            document.add(Paragraph("Financial Stress Score: ${analysis.stressScore}/100"))
            document.add(Paragraph("Risk Level: ${analysis.riskLevel.name}"))
            document.add(Paragraph("Suggested Safe EMI Limit: ₹${String.format("%.2f", analysis.suggestedSafeEmiLimit)}"))
            document.add(Paragraph("Suggested Minimum Savings: ₹${String.format("%.2f", analysis.suggestedMinSavings)}"))
            
            document.add(Paragraph("\n--- Recommendations ---").setBold())
            analysis.suggestions.forEach { suggestion ->
                document.add(Paragraph("• $suggestion"))
            }
            
            document.add(Paragraph("\n\n---\nGenerated by EMI Trap Alert - Debt Stress Analyzer")
                .setFontSize(10f))
            
            document.close()
            
            return file
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }
}
